#!/usr/bin/env bash
# usage:
#
# ./ci-build-binary <binary>
#
# where <binary> is one of: espresso-node, espresso-node-sqlite, espresso-dev-node, other
#
set -euo pipefail

case "$1" in
    "espresso-node")
        cargo build --locked --release --timings -p espresso-node --bin espresso-node
        ;;
    "espresso-node-sqlite")
        cargo build --locked --release --timings -p espresso-node-sqlite
        ;;
    "espresso-dev-node")
        cargo build --locked --release --timings -p espresso-dev-node
        ;;
    "staking-cli")
        cargo build --locked --release --timings -p staking-cli --bin staking-cli
        ;;
    "other")
        BINS="$(cargo metadata --no-deps --format-version 1 \
        | jq -r '.packages[].targets[] | select(.kind[] == "bin") | .name' \
        | grep -v '^espresso-node$\|^espresso-node-sqlite$\|^espresso-dev-node$\|^staking-cli$' \
        | xargs -I{} echo --bin {} \
        | tr '\n' ' ')"
        echo "Building other binaries: $BINS"
        cargo build --locked --release --timings $BINS
        ;;
    *)
        echo "Unknown binary: $1"
        exit 1
        ;;
esac
