name: Cargo features

on:
  workflow_dispatch:
concurrency:
  # ensure non-PR jobs run in parallel
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_INCREMENTAL: "0"

jobs:
  cargo-features:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - just check-features-ci
          - just check-features-ci --tests
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/free-disk-space

      - name: Install Protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - uses: taiki-e/install-action@cargo-hack
      - uses: taiki-e/install-action@just
      # Note: this job doesn't use a cache on purpose because it mostly compiles
      # the crates in this repo over and over again with different feature
      # combinations. The target directory gets really large. Adding caching
      # would not speed it up much and further contribute to our cache usage.
      - name: Check compilation feature combinations
        run: |
          ${{ matrix.command }}
