name: Docs
on:
  workflow_dispatch:
concurrency:
  # ensure non-PR jobs run in parallel
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_INCREMENTAL: "0"

jobs:
  doc-rust:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - uses: taiki-e/install-action@just

      - name: Build Rust Docs
        run: just doc

      - name: Upload Rust Docs
        uses: actions/upload-artifact@v7
        with:
          name: rust-docs
          path: target/doc
          if-no-files-found: error
          retention-days: 1

  doc-contracts:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Foundry
        uses: ./.github/actions/install-foundry

      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@mdbook

      - name: Build Contract Docs
        run: just doc-contracts

      - name: Upload Contract Docs
        uses: actions/upload-artifact@v7
        with:
          name: contract-docs
          path: docs/book
          if-no-files-found: error
          retention-days: 1

  deploy:
    needs: [doc-rust, doc-contracts]
    runs-on: ubuntu-24.04
    steps:
      - name: Download Rust Docs
        uses: actions/download-artifact@v8
        with:
          name: rust-docs
          path: public

      - name: Download Contract Docs
        uses: actions/download-artifact@v8
        with:
          name: contract-docs
          path: public/contracts

      - name: Create Index
        run: echo '<meta http-equiv="refresh" content="0; url=espresso_node">' > public/index.html

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: espresso-network.docs.espressosys.com
