name: Slow Test

on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'main')}}

# Build test binary with `testing` feature, which requires `hotshot_example` config
env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info,libp2p=off,node=error
  NEXTEST_PROFILE: slow
  CARGO_INCREMENTAL: "0"

jobs:
  slow-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: slow-tests-sqlite
            build-cmd: just test-slow --features embedded-db --no-run
            run-cmd: just test-slow --features embedded-db --no-fail-fast
          - name: slow-tests-postgres
            build-cmd: just test-slow --no-run
            run-cmd: just test-slow --no-fail-fast
          - name: espresso-dev-node-tests
            build-cmd: just test-dev-node --no-run
            run-cmd: just test-dev-node --no-fail-fast

    name: ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/free-disk-space

      - name: Install Protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - uses: ./.github/actions/install-foundry
      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@nextest
      - uses: rui314/setup-mold@v1

      - name: Enable Rust Caching
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.name }}
          save-if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release-') }}

      - name: Build slow test
        run: ${{ matrix.build-cmd }}

      - name: Run slow test
        run: ${{ matrix.run-cmd }}
        timeout-minutes: 90

      - name: Show available disk space
        if: always()
        run: |
          df -h
