name: Typos

on:
  workflow_dispatch:
concurrency:
  # ensure non-PR jobs run in parallel
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout Repository

      - name: typos-action
        uses: crate-ci/typos@v1.32.0
